name: Deploy Backend

on:
  push:
    branches: [ master ]
    paths:
      - 'Backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd Backend
          npm install
          
      - name: Build
        run: |
          cd Backend
          npm run build
          
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Backend/dist/*"
          target: "/var/www/licensing/Licensing-Server/Backend/dist/"
          
      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/licensing/Licensing-Server/Backend
            npm install
            
            # Set proper permissions for the deployed files
            chmod -R 755 /var/www/licensing/Licensing-Server/Backend/dist
            
            # Check if process exists and restart or start accordingly
            pm2 describe licensing-backend > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart licensing-backend
            else
              pm2 start ecosystem.config.js
            fi
            
            # Save PM2 process list for persistence after reboot
            pm2 save
            
            # Verify deployment
            echo "===== DEPLOYMENT VERIFICATION ====="
            echo "Checking PM2 processes:"
            pm2 list
            echo "Checking deployed files:"
            ls -la /var/www/licensing/Licensing-Server/Backend/dist/
            echo "=============================="