name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd Frontend
          npm install
          
      - name: Build
        run: |
          cd Frontend
          npm run build
          
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Frontend/dist/*"
          target: "/var/www/licensing/frontend/"
          
      - name: Set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            chown -R www-data:www-data /var/www/licensing/frontend
            chmod -R 755 /var/www/licensing/frontend
            systemctl restart apache2 