name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy source files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Frontend/*"
          target: "/var/www/licensing/Licensing-Server/Frontend/"
          strip_components: 1
          
      - name: Build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/licensing/Licensing-Server/Frontend
            npm install
            npm run build
            
      - name: Deploy compiled files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "/var/www/licensing/Licensing-Server/Frontend/dist/*"
          target: "/var/www/licensing/frontend/"
          strip_components: 1
          
      - name: Restart Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo /usr/local/bin/restart-apache.sh 