name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd Frontend
          npm install
          
      - name: Build
        run: |
          cd Frontend
          npm run build
          
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Frontend/dist/*"
          target: "/var/www/licensing/Licensing-Server/Frontend/dist/"
          strip_components: 2
          
      - name: Configure Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Set proper permissions for the deployed files
            chmod -R 755 /var/www/licensing/Licensing-Server/Frontend/dist
            
            # Create .htaccess file for SPA routing
            cat > /var/www/licensing/Licensing-Server/Frontend/dist/.htaccess << 'EOL'
            <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteBase /
              RewriteRule ^index\.html$ - [L]
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteRule . /index.html [L]
            </IfModule>
            EOL
            
            # Reload Apache to apply changes
            sudo systemctl reload apache2
            
            # Verify deployment
            echo "===== DEPLOYMENT VERIFICATION ====="
            echo "Checking deployed files:"
            ls -la /var/www/licensing/Licensing-Server/Frontend/dist/
            echo "=============================="

      - name: Cache busting (if needed)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Optional: Clear any caches if necessary
            # redis-cli flushall 