name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd Frontend
          npm install
          
      - name: Build
        run: |
          cd Frontend
          npm run build
          
      - name: Clean remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/licensing/*
            sudo mkdir -p /var/www/html/licensing
            sudo chown -R ${{ secrets.SERVER_USERNAME }}:www-data /var/www/html/licensing
            sudo chmod -R 775 /var/www/html/licensing
          
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Frontend/dist/*"
          target: "/var/www/html/licensing/"
          strip_components: 1
          overwrite: true
          
      - name: Set permissions and restart Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo /usr/local/bin/deploy-frontend.sh 